name: YouTube Shorts Automation

on:
  schedule:
    - cron: "0 */5 * * *"   # ‚è∞ Har 5 ghante chalega
  workflow_dispatch:         # üîò Manual run ka option bhi hoga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ‚úÖ Checkout with pinned SHA
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.1.7

      # ‚úÖ Setup Python with pinned SHA
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.7.1
        with:
          python-version: "3.11"

      # ‚úÖ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # ‚úÖ Run main.py
      - name: Run script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
